---
- name: Configure MOTD and update-motd.d permissions
  hosts: Wazuh
  become: yes  # Use sudo privileges for modifying system files
  tasks:
    - name: Overwrite /etc/motd with custom message
      become: yes 
      become_user: root
      copy:
        dest: /etc/motd
        content: |
          We trust you have received the usual lecture from local System Administrator. It usually boils down to these three things. 
          (1) Respect the privacy of others.
          (2) Think before you type.
          (3) With great power comes great responsibility.
        force: yes  # Ensure the file is overwritten regardless of content
        mode: '0644'
        owner: root
        group: root
        unsafe_writes: true
      


