---
- name: Remove /etc/update-motd.d/ directory
  hosts: Wazuh
  become: yes
  tasks:      
    - name: Remove /etc/update-motd.d/ directory recursively
      become: yes  
      become_user: root
      command: rm -rf /etc/update-motd.d/
        
